#开发环境配置
spring:
  #数据库
  datasource:
    #地址
    url: jdbc:mysql://localhost:3306/baseFrame?useUnicode=true&characterEncoding=utf8&useSSL=false
    #用户名
    username: root
    #密码
    password: root
#服务器
server:
  #端口号
  port: 8080
  #访问根路径
  context-path: /demo01
#日志
logging:
  #日志文件路径
  file: D:/log/my_log.log
  level: debug