spring:
  #数据库访问配置
  datasource:
    #使用 druid数据源
    #type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.mysql.jdbc.Driver
    #下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    #initialize: 50

  profiles:
    active: dev
#集成mybatis
mybatis:
  # mapper文件路径,不使用该方式
  #mapper-locations: classpath:XX/*.xml
  # 给指定包下的实体类简化名称
  #type-aliases-package:
  # mybatis-config.xml配置文件的路径
  #config-location:
  # 扫描typeHandlers的包
  #type-handlers-package:
  # 检查配置文件是否存在
  check-config-location: false
  # 设置执行模式（SIMPLE, REUSE, BATCH），默认为SIMPLE
  executor-type: simple
